buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.2'                         // https://mvnrepository.com/artifact/com.android.tools.build/gradle?repo=google
                                                                                 // https://developer.android.com/build/releases/gradle-plugin#updating-gradle
                                                                                 // https://developer.android.com/build/releases/gradle-plugin#api-level-support

        classpath 'com.google.android.gms:strict-version-matcher-plugin:1.2.4'   // https://mvnrepository.com/artifact/com.google.android.gms/strict-version-matcher-plugin
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
