project.ext {
    applicationId      = 'com.github.warren_bank.exoplayer_airplay_receiver'

    releaseVersionCode = Integer.parseInt("003140623", 10)  //Integer.MAX_VALUE == 2147483647
    releaseVersion     = '003.14.06-23API'
    javaVersion        = JavaVersion.VERSION_17             //https://docs.gradle.org/8.9/javadoc/org/gradle/api/JavaVersion.html
    minSdkVersion      = 23

    // [Android 11+] if (targetSdkVersion >= 30), error: NetworkUtils.getMACAddress()
    //   see: https://developer.android.com/training/articles/user-data-ids#mac-11-plus

    targetSdkVersion   = 36 //29
    compileSdkVersion  = 36
    buildToolsVersion  = '36.1.0'

    libVersionDdPlist        = '1.23'
    libVersionJmDNS          = '3.5.8'
    libVersionAndroidxMedia3 = '1.11.0'

    // keep versions of AndroidX libraries in sync with those used by AndroidX Media3:
    //   https://github.com/androidx/media/blob/1.11.0/gradle/libs.versions.toml#L21

    libVersionAndroidxAnnotation = '1.6.0'
    libVersionAndroidxAppCompat  = '1.6.1'
    libVersionAndroidxCore       = '1.9.0'
    libVersionAndroidxMedia      = '1.7.0'
    libVersionAndroidxMaterial   = '1.8.0'
}
