project.ext {
    applicationId      = 'com.github.warren_bank.exoplayer_airplay_receiver'

    releaseVersionCode = Integer.parseInt("003130123", 10)  //Integer.MAX_VALUE == 2147483647
    releaseVersion     = '003.13.01-23API'
    javaVersion        = JavaVersion.VERSION_1_8
    minSdkVersion      = 23

    // [Android 11+] if (targetSdkVersion >= 30), error: NetworkUtils.getMACAddress()
    //   see: https://developer.android.com/training/articles/user-data-ids#mac-11-plus

    targetSdkVersion   = 35 //29
    compileSdkVersion  = 35
    buildToolsVersion  = '34.0.0'

    libVersionDdPlist        = '1.23'
    libVersionHttpCore       = '4.4.13'
    libVersionJmDNS          = '3.5.8'
    libVersionAndroidxMedia3 = '1.9.0-alpha01'

    // keep versions of AndroidX libraries in sync with those used by AndroidX Media3:
    //   https://github.com/androidx/media/blob/1.9.0-alpha01/constants.gradle#L42

    libVersionAndroidxAnnotation = '1.6.0'
    libVersionAndroidxAppCompat  = '1.6.1'
    libVersionAndroidxCore       = '1.8.0'
    libVersionAndroidxMedia      = '1.7.0'
    libVersionAndroidxMaterial   = '1.8.0'
}
